movie_app/urls.py
from . import views
from django.urls import path

app_name = 'movie_app'    #name space

urlpatterns = [

    path('', views.index, name='index'),
    path('movie/<int:movie_id>', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movie_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_app/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField(max_length=4)
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie_app/forms.py
from django import forms
from .models import Movie

class Movie_form(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'year', 'desc', 'img']

movie_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import Movie
from . forms import Movie_form
# Create your views here.

def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list' : movie
    }
    return render(request,'index.html', context)

def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "detail.html", {"movie": movie})

def add_movie(request):
    if request.method=='POST':
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')
    return render(request, 'add.html')

def update(request, id):
    movie = Movie.objects.get(id=id)
    form = Movie_form(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form':form, 'movie':movie})

def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Your form fields here -->
    <input type="text" name="name" placeholder="Enter the movie name"><br><br>
    <input type="text" name="year" placeholder="Enter the movie's release year"><br><br>
    <input type="text" name="desc" placeholder="Enter the movie's description"><br><br>
    <input type="file" name="img" placeholder="Add an image"><br><br>
    <input type="submit">
    <br>
    <br>
</form>
{% endblock %}

templates/backup.html
<style>
    .movie-card {
        margin-bottom: 10px;
        padding-bottom: 10px;
        padding-top: 10px;
        width: 16rem; /* Set the desired width for the cards */
        height: 100%; /* Set the desired height for the cards */
        }
</style>

<nav class="navbar navbar-dark bg-dark">

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark navbar-custom">
  <a class="navbar-brand" href="#">
    Movie Cart
  </a>
  <a class="btn button1 ml-auto" href="{% url 'movie_app:add_movie'  %}">Add Movie</a>
</nav>

{% block body %}

{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <style>
        /* Add CSS styles here */
        body {
            color: white;
        }
    </style>
    are you sure you want to delete this  <br><br>
    <input type="submit">
</form>

{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
  <img src="{{movie.img.url}}" class="movie-image">
</div>
<div class="col-md-6">
  <h6 class="movie-name">{{movie.name}}</h6>
  <h6 class="movie-desc">{{movie.desc}}</h6>
  <h6 class="movie-year">{{movie.year}}</h6>
  <a class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">Update</a>
  <a class="btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">Delete</a>
</div>


    </div>

</div>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<form method="POST" enctype="multipart/form-data">

    {% csrf_token %}

    <style>
        /* Add CSS styles here */
        body {
            color: white;
        }
    </style>

    {{form.as_p}}
    <button type="submit" class="save btn button1">Save</button>

</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3 movie-card">
            <div class="card card_edit">
                <img class="card-img-top" src="{{ i.img.url }}" alt="Card image cap" height="250px">
                <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <p class="card-text">{{ i.desc }}</p>
                    <a class="btn btn-primary" href="{% url 'movie_app:detail' i.id %}">More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<br>

{% endblock %}